name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build: 
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@v1
      -   name: Setup Enviroment
          uses: frogmarketmedia/setup-php@v1
          with:
            php-version: '7.4'
      -   name: Speed up the packages installation process
          run: composer global require hirak/prestissimo
      -   name: Install Packages
          run: composer install --no-dev
      -   name: Deploy to Server
          uses: frogmarketmedia/deploy@laravel
          with:
              user: forge
              host: 167.99.98.182
              path: /home/erik-smith-5ee5e33045c17/juliandsmith.com
              owner: frogmarketmedia
          env:
              DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
